site_name: The Road to Elysium
site_url: https://jorge.fbarr.net

theme:
  name: material
  font:
    text: Inconsolata
  palette: 
    - scheme: slate
  features:
    - navigation.path

nav:
  - Home: index.md
  - About: about.md

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
      blog_dir: .
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jorgeebarrera/
    - icon: fontawesome/brands/github
      link: https://github.com/joenba7

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
