site_name: The Road to Elysium
site_url: https://jorge.fbarr.net
copyright: >
    <p xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0</a> - Jorge Enrique Barrera</p>

theme:
  name: material
  custom_dir: overrides
  font:
    text: Inconsolata
  palette: 
    - scheme: slate
  features:
    - navigation.path
    - content.code.copy
    - content.code.select

nav:
  - Home: index.md
  - About: about.md

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
      blog_dir: .
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jorgeebarrera/
    - icon: fontawesome/brands/github
      link: https://github.com/joenba7
  analytics:
    provider: google
    property: G-6Y65E84W34

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

